### ISSUE TITLE
DD1: Incorrect speed in introduction sequence

### ISSUE THREAD

**Issue by protogem2** [jotego/jtdd#7]
The introduction sequence plays very quickly compared to an original Double Dragon pcb, usually this the speed is lower until gameplay starts:  

https://www.youtube.com/watch?v=gJcoJwWdM6I

**Comment by jotego** [comment]
Thank you very much for the original footage.
 
There is a good chance that the ROM sets are different. Double Dragon presents wild speed differences across ROM sets.

I am not sure how you can determine your version other than an actual ROM dump.

**Comment by protogem2** [comment]
Retrodriven provides the following alternative sets, that all have the same too fast introduction:

Double Dragon (bootleg)
Double Dragon (US Set 1)
Double Dragon (US set 2)
Double Dragon (World Set 1)
Double Dragon (World Set 2)

Here are some more reference videos.

US Set 2 (Mame): https://www.youtube.com/watch?v=Q4aFNr8m8_c
US set 3 (Mame): https://www.youtube.com/watch?v=-xEkO3ftsf0

MAME does not behave like the core does in the introduction, for the same rom sets. Nor do any of the PCBs with footage on youtube. Having owned my own pcb some years ago I can state it did not act like the core either.

In the readme it states you compared the core to a real Double Dragon pcb, can you confirm the intro ran quickly on this pcb?

**Comment by jotego** [comment]
For Double Dragon 1 there are schematics available (you can find them in the **doc** folder of this repository) so I only verified that the schematics did reflect the PCB and then worked off the schematics. For Double Dragon 2, there are no schematics so I had to measure the board. You can also see the measurements in the same folder.

I have tried several DIP settings, as sometimes these things are purely software. We already had a similar issue in GunSmoke that turned out to be due to a side effect of a DIP setting. I've tried some combinations in MAME and the punch to the girl always seemed slower in MAME than in JTDD. So maybe it isn't software.

Double Dragon 1 uses a microcontroller (MCU) to handle the sprites. Although the connection between that MCU and the main CPU is accurate and according to the schematics; the MCU itself may not be accurate.

The MCU is a 63701 for which I was not able to find any working IP (Intellectual Property, ie a piece of source code that someone has already done and tested). I had to use a compatible M6801 and add the extra MCU logic externally. The M6801 used seems to be unmantained currently and couldn't locate the author. I have no guarantee that it is cycle accurate and have to check it at some point. This CPU or the MCU variant are not extremely popular and the task to correct for cycle accuracy is not trivial and probably involves some two weeks of work. So it is not high in my to-do list.

As a work around I had planned to measure the MCU periods on the PCB -as already done for DD2- and adjust the clock speed of the integrated MCU to match them. This is a high level tuning. Not as good as having a cycle accurate MCU core but it would improve the timing. It is also a quick way of asserting whether or not the MCU core is cycle accurate.

I cannot assure that the problem is in the software (a side effect of a specific DIP setting) or in the hardware (an MCU that goes a bit too fast). But measuring the MCU periods in the PCB and comparing with the integrated MCU is the next action for me.

**Comment by jotego** [comment]
Even after the accuracy fix for the M6809 in commit https://github.com/jotego/jtdd/commit/716adbf1d4aac29d5d423f0fd531a937b55f0789, this still seems to happen. I still think the culprit is the M6801 IP.

**Comment by gyurco** [comment]
Just for record, I link my solution here, too:
https://github.com/gyurco/jtdd/commit/7b3556fffb42f1795c975385d2503175355e8ecb

**Comment by jotego** [comment]
Thanks @gyurco for pointing out that the assigned clock speed in the RTL code was wrong. I could not use your commit directly because it contained the 96MHz clock change for DD2 too, but I have replicated it ([commit](https://github.com/jotego/jtdd/commit/178a766278fbfff7414956e1d0588bf49343c461))

For reference, the HCLK used is 12MHz/2 = 6MHz

![image](https://user-images.githubusercontent.com/1863036/91653613-a1e59280-eaa2-11ea-97cd-6ac80db56735.png)

For the sound CPU I had mistakenly assigned 12 instead of 6. I think this was just a typo.

But for the MCU I had the right 6MHz clock connected

![image](https://user-images.githubusercontent.com/1863036/91653647-eb35e200-eaa2-11ea-8471-e3f5e1fd9d64.png)

But I had missed that contrary to HD63701V0, the HD63701Y0 variation has an internal four divider for the clock pin:

![image](https://user-images.githubusercontent.com/1863036/91653743-a52d4e00-eaa3-11ea-82b6-555077c9e767.png)

So the right speed for the M6801 module was 1.5MHz not 6MHz.

I have uploaded updated binary files for all three platforms [to jtbin](https://github.com/jotego/jtbin/commit/e5a4439c35df14fb6c1758dd4cf460b4686f248c) too.
